version: '3'

services:
  scraper:
    build: .
    volumes:
      - ./data/scraped_posts:/app/data/scraped_posts
      - ./data/temp_images:/app/data/temp_images
      - ./shorpy_data.db:/app/shorpy_data.db
      - ./.env:/app/.env
    environment:
      - TZ=Asia/Nicosia
    restart: unless-stopped
    command: python main.py --schedule --silent --report-to 29909617 