name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running tests'
        required: false
        default: 'Manual trigger'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-asyncio
        
    - name: Test args parsing
      run: |
        python -m tests.test_args
        
    - name: Run integration tests
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd) python -m pytest tests/test_integration.py -v
        
    - name: Run app with validation
      run: |
        python main.py --validate --silent 